export const GET_USER_PROFILE_LOADING = 'GET_USER_PROFILE_LOADING';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const SEARCH_FOR_SONGS_LOADING = 'SEARCH_FOR_SONGS_LOADING';
export const SEARCH_FOR_SONGS_SUCCESS = 'SEARCH_FOR_SONGS_SUCCESS';
export const SEARCH_FOR_SONGS_ERROR = 'SEARCH_FOR_SONGS_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_NEW_RELEASES_LOADING = 'GET_NEW_RELEASES_LOADING';
export const GET_NEW_RELEASES_SUCCESS = 'GET_NEW_RELEASES_SUCCESS';
export const GET_NEW_RELEASES_ERROR = 'GET_NEW_RELEASES_ERROR';

export const GET_USER_SEARCH_RESULT_LOADING = 'GET_USER_SEARCH_RESULT_LOADING';
export const GET_USER_SEARCH_RESULT_SUCCESS = 'GET_USER_SEARCH_RESULT_SUCCESS';
export const GET_USER_SEARCH_RESULT_ERROR = 'GET_USER_SEARCH_RESULT_ERROR';

export const MANAGE_LIBRARY_LOADING = 'MANAGE_LIBRARY_LOADING';
export const MANAGE_LIBRARY_SUCCESS = 'MANAGE_LIBRARY_SUCCESS';
export const MANAGE_LIBRARY_ERROR = 'MANAGE_LIBRARY_ERROR';
export const REMOVE_TRACK_FROM_LIBRARY = 'REMOVE_TRACK_FROM_LIBRARY';

export const DELETE_FROM_LIBRARY_LOADING = 'DELETE_FROM_LIBRARY_LOADING';
export const DELETE_FROM_LIBRARY_SUCCESS = 'DELETE_FROM_LIBRARY_SUCCESS';
export const DELETE_FROM_LIBRARY_ERROR = 'DELETE_FROM_LIBRARY_ERROR';

export const GET_USER_LIBRARY_LOADING = 'GET_USER_LIBRARY_LOADING';
export const GET_USER_LIBRARY_SUCCESS = 'GET_USER_LIBRARY_SUCCESS';
export const GET_USER_LIBRARY_ERROR = 'GET_USER_LIBRARY_ERROR';

export const EXPORT_TO_SPOTIFY_PLAYLIST_LOADING =
  'EXPORT_TO_SPOTIFY_PLAYLIST_LOADING';
export const EXPORT_TO_SPOTIFY_PLAYLIST_SUCCESS =
  'EXPORT_TO_SPOTIFY_PLAYLIST_SUCCESS';
export const EXPORT_TO_SPOTIFY_PLAYLIST_ERROR =
  'EXPORT_TO_SPOTIFY_PLAYLIST_ERROR';

export const GET_ALBUM_TRACKS_LOADING = 'GET_ALBUM_TRACKS_LOADING';
export const GET_ALBUM_TRACKS_SUCCESS = 'GET_ALBUM_TRACKS_SUCCESS';
export const GET_ALBUM_TRACKS_ERROR = 'GET_ALBUM_TRACKS_ERROR';
