export const GET_USER_PROFILE_LOADING = 'GET_USER_PROFILE_LOADING';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const SEARCH_FOR_SONGS_LOADING = 'SEARCH_FOR_SONGS_LOADING';
export const SEARCH_FOR_SONGS_SUCCESS = 'SEARCH_FOR_SONGS_SUCCESS';
export const SEARCH_FOR_SONGS_ERROR = 'SEARCH_FOR_SONGS_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
